# Generated by Django 4.2.6 on 2023-10-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='option1',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option2',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option3',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option4',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question',
            field=models.CharField(max_length=2000),
        ),
    ]
