# Generated by Django 4.2.6 on 2023-10-15 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppQuiz', '0002_alter_mcq_option1_alter_mcq_option2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='quizmcq',
        ),
        migrations.AddField(
            model_name='mcq',
            name='quiz',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quizmcq', to='AppQuiz.quiz'),
            preserve_default=False,
        ),
    ]
