# Generated by Django 4.2.6 on 2023-10-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppForum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created']},
        ),
    ]
