# Generated by Django 4.2.6 on 2023-10-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppForum', '0002_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answerquestion', to='AppForum.question'),
            preserve_default=False,
        ),
    ]
