# Generated by Django 4.2.6 on 2023-10-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppForum', '0003_answer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created']},
        ),
    ]
